name: provider_shopper
description: A shopping app sample that uses Provider for state management.
publish_to: none

version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  go_router: ^12.1.1
  provider: ^6.0.2
  window_size:
    git:
      url: https://github.com/google/flutter-desktop-embedding.git
      path: plugins/window_size
  dio: ^5.4.2+1
  dio_cookie_manager: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.13.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Corben
      fonts:
        - asset: fonts/Corben/Corben-Bold.ttf
          weight: 700
